name: hogehoge

on:
  push:
    branches:
      - main
      - hoge
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: check github head_ref
      run: echo ${{ github.head_ref }}
    - name: check github ref_name
      run: echo ${{ github.ref_name }}
